STATUS_ACTIVE = 1
STATUS_INACTIVE = 2
STATUS_PENDING = 3
STATUS_DELETED = 11

ROLE_USER = 1
ROLE_ADMIN = 10

ACL_READ = 1
ACL_WRITE = 2
ACL_ADMIN = 5
ACL_OWNER = 10

LOCATION_SOURCE_SELF = 1
LOCATION_SOURCE_GEONAME = 10
LOCATION_SOURCE_GOOGLE_MAP_SHAPE = 11
